services:
  db:
    image: postgres:latest
    container_name: frog-fund
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
